### ISSUE TITLE
Where do I download the complied .jar file

### ISSUE THREAD

**Issue by y2kman** [Graylog2/graylog-plugin-threatintel#104]
I know that this is a newbie question so don't laugh.  I currently have version 2.4.5 running on my graylog server which I setup from their already configured virtual appliance.  I'm wondering how I can obtain the .jar file for your alpha or beta versions so that I can install into Graylog.

**Comment by joschi** [comment]
@y2kman The Threat Intelligence plugin is distributed with Graylog since Graylog 2.4.0. You don't need to download it separately.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
